######## Default Configs ##########
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  freemarker:
    enabled: false
    template-loader-path: classPath:/templates/mail-template
    suffix: .ftl
  mail:
    default-encoding: UTF-8
    host: mail.ishanitech.com
    username: no-reply@ishanitech.com
    password: ENC(ykBbW2svEwwW2W4foyFvQtHVGLKzMHH9)
    port: 587
    properties:      
      mail:
        smtp:
          auth: true
        starttls:
          enabled: true
    protocol: smtp
  resources:
    cache:
      cachecontrol:
        max-age: 36000

server:
  error:
    whitelabel:
      enabled: false

---

###### Development Config Properties #######
spring:
  profiles: dev
server:
  port: 9191
  
rest-api:
  protocol: http
  domain: localhost
  port: 8888
  
com:
  tempFileUploadingDirectory: C:/upload-dir/  
---

####### ishani Production Config Properties ########
spring:
  profiles: prod
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: /home/ishani/keystore/ipasal.p12
    key-store-password: ENC(bq4tjhncoATdejotP81VbWgaGMpRouOZ)
    key-alias: ipasal
#### Rest api base address #####   
rest-api:
  protocol: http
  domain: 103.233.58.121
  port: 8888
  
  
com:
  ipalika:
    tempFileUploadingDirectory: /home/ishani/Pictures/ 